# tasks file for k8s-worker

  - name: "Installing docker"
    package: 
      name: docker
      state: present

  - name: "Starting docker services"
    service:
     name: docker
     state: restarted

  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      exclude=kubelet kubeadm kubectl

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a
    when: ansible_swaptotal_mb > 0

  - name: configuring sysctl.conf
    copy:
      src: /etc/sysctl.conf
      dest: /etc/sysctl.conf
  - name: reloading sysctl.conf file
    command: sudo sysctl -p


  - name: Installing required packages
    yum:
     name: "kubelet, kubeadm, kubectl " 
     state: present
     disable_excludes: kubernetes
    
  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Creating folder for daemon.json
    file:
     path: /etc/docker/daemon.json
     state: touch
    
  - name: copying content of the daemon.json file
    copy:
      dest: /etc/docker/daemon.json
      src:  daemon.json

  - name: installing iproute-tc
    package:
      name:
      - iproute-tc
      state: present

  - name: enabling docker service
    service:
      name: "docker"  
      state: restarted
      enabled: yes

  - name: enabling kubelet service
    service:
      name: "kubelet"
      state: started
      enabled: yes

  - name: Refreshing sysctl
    shell: "sysctl --system"
  
  - name: Copy the join command to server location
    copy: src=./join-command dest=/tmp/join-command.sh mode=0777

  - name: Join the node to cluster
    command: sh /tmp/join-command.sh


